### ISSUE TITLE
TGA color map decoding

### ISSUE THREAD

**Issue by nickbabcock** [nickbabcock/Pfim#18]
Right now tga color map decoding is very dumb. It simply reads it into a `byte[]`. While quick and painless, it's not ergonomic and I haven't provided a sample of how to make a color mapped image display correctly.

I'm curious if it is worth applying the color map to the decoded image and not worry about exposing the color map to users.

**Comment by Krakean** [comment]
@nickbabcock Why not provide a flag so user can control this behaviour in particular case?
Or as an option take a look at https://github.com/ALEXGREENALEX/TGASharpLib how this lib handle it

**Comment by nickbabcock** [comment]
I'm closing this as Pfim 0.6.0 now has `ApplyColorMap` which allows one to opt into have the tga color map applied (and in the process update data and other properties). Probably not the last improvement to colormap support but it is much better than the opaque byte array. Future issues can expand upon this.
