### ISSUE TITLE
Unrecognized PixelDepth 0

### ISSUE THREAD

**Issue by feliwir** [nickbabcock/Pfim#2]
The file attached isn't loaded properly for some weird reason. Every image editor with dds support loads it competly fine. Help is appreciated

Here is the file:
https://mega.nz/#!DoxnibhD!GVFgFv6niRj8VS1mFAwXu975mxr0CdbgEMoq5DX_93g

**Comment by nickbabcock** [comment]
I wouldn't doubt it is a bug with this library, as the [test data](https://github.com/nickbabcock/Pfim/tree/a98e13d37f8e64e9528c5f22baf79ba8eccdaea3/tests/Pfim.Tests/data) is quite small. I'll take a look at the image, and add it as a test case.

**Comment by nickbabcock** [comment]
Bugfixed in version 0.3.1 that was released a couple minutes ago.

**Comment by feliwir** [comment]
Thanks, will the nuget package get updated aswell?
