### ISSUE TITLE
Support for A8R8G8B8 and P8 (DDS)

### ISSUE THREAD

**Issue by LeoCodes21** [nickbabcock/Pfim#24]
Hi,

I'm making a DDS texture viewer for an old game, and some textures use DDS formats that are unsupported by this library. The 2 formats are A8R8G8B8 (0x15, 21), and P8 (0x29, 41). 

When I try to use the library to load the generated DDS stream, it raises an exception: "FourCC: [21/41] not supported".

I'd appreciate it if support was added for these 2 formats. It's not terribly important, but simply something that would be nice to have, as these 2 formats aren't entirely uncommon.

If example files are needed, I can provide them.

Thanks for your time, and for this excellent library! It easily beats anything else I've used in the past for this purpose.

**Comment by nickbabcock** [comment]
Glad you find it useful! I'm on holiday at the moment, but if you have example files (if I can't commit them to the repo let me know), I can personally test them out and ensure they are working when I return
________________________________

**Comment by LeoCodes21** [comment]
[textures.zip](https://github.com/nickbabcock/Pfim/files/2325246/textures.zip)
Don't commit, please; thanks :-)

**Comment by nickbabcock** [comment]
* What version of pfim are you using?
* The images in you zip, are they the ones that you receive the error on?

I ask because both images loaded fine in the Pfim.Viewer.Forms sample project in this repo.

**Comment by LeoCodes21** [comment]
- 0.5.2.0
- Yes; all textures of the 2 types cause errors for me.

That is interesting; perhaps I did something wrong in my code. I will investigate, thanks.

**Comment by nickbabcock** [comment]
No problem, I'll leave this open for another week or two and then I'll close it (but this can always be re-opened)

**Comment by nickbabcock** [comment]
(finally getting around to closing this)
