### ISSUE TITLE
Converting to System.Drawing.Image

### ISSUE THREAD

**Issue by paulherman** [nickbabcock/Pfim#3]
Hi!

How would I go about converting an IImage to System.Drawing.Image? It gives me access to the raw bytes, but there is no way of getting only the pixel values rather than the whole file (i.e. with headers). Has this been considered or is there some trick I'm not aware of?

**Comment by nickbabcock** [comment]
To clarify the `data` that IImage contains does not contain the header, but only the color data. I don't have the code right on hand, but I believe you can utilize this [Bitmap constructor](https://msdn.microsoft.com/en-us/library/zy1a2d14(v=vs.110).aspx) to get your `System.Drawing.Image`. If you figure it out, I'll add it to the docs 😉 

additional resources:

- [How to get IntPtr from byte[] in C#](http://stackoverflow.com/q/537573/433785)

**Comment by paulherman** [comment]
I tried to do that and it seemed like data.Length was not equal to stride * width. It might've been a mistake on my side. Will try again probably tomorrow and report back.

Thank you!

**Comment by nickbabcock** [comment]
If possible / reasonable, try Pfim 0.4.2 released for netstandard and contains several bug fixes that may pertain to the issue you were seeing.

If no more feedback, I'll close the issue.

**Comment by nickbabcock** [comment]
I'll close this as I included a sample windows forms app in the source code. I've include the relevant snippet in the docs (but I'll leave it hear for redundancy):

```csharp
var image = Pfim.FromFile(dialog.FileName);

PixelFormat format;
switch (image.Format)
{
    case ImageFormat.Rgb24:
        format = PixelFormat.Format24bppRgb;
        break;

    case ImageFormat.Rgba32:
        format = PixelFormat.Format32bppArgb;
        break;

    default:
        throw new Exception("Format not recognized");
}

unsafe
{
    fixed (byte* p = image.Data)
    {
        var bitmap = new Bitmap(image.Width, image.Height, image.Stride, format, (IntPtr) p);
        pictureBox.Image = bitmap;
    }
}
```
