### ISSUE TITLE
Infinite hang decoding 1x1 DDS

### ISSUE THREAD

**Issue by jzebedee** [nickbabcock/Pfim#30]
When a [1 x 1 DDS](https://github.com/nickbabcock/Pfim/files/3000025/horse_male_clothes_behind.zip) is decoded, the blocks per stride is 0

https://github.com/nickbabcock/Pfim/blob/68d957e0fe72dee1e53e96cc827162f7ba3c68a2/src/Pfim/dds/CompressedDds.cs#L41

which will lead to no Decode being performed.

When the length is subtracted from `pixelsLeft`, it will overflow and wrap around to `uint.MaxValue`.

https://github.com/nickbabcock/Pfim/blob/68d957e0fe72dee1e53e96cc827162f7ba3c68a2/src/Pfim/dds/CompressedDds.cs#L94

This causes the method to loop indefinitely.

**Comment by nickbabcock** [comment]
Thanks for the bug report! I hope to get this fixed soon.

**Comment by nickbabcock** [comment]
Pfim 0.6.0 has been released with this bugfix, thank you for the report.

**Comment by jzebedee** [comment]
Great! Thanks for the quick fix.
