### ISSUE TITLE
Array out of bounds Exception when open some DDS Files

### ISSUE THREAD

**Issue by draconas1** [nickbabcock/Pfim#31]
I'm making a mod parser for Stellaris, where most of the UI icons are stored as DDS images.

Most parse, but some of them get "Index was outside the bounds of the array" when calling Pfim.Pfim.FromFile

Sample images that have failed to load: https://drive.google.com/open?id=1NRYCqqh1C_vvLgKUHQxzoVXYq6g2CGfc 

Apologies, I do not understand DDS files well enough to know what is different and causing it to fail while others load fine.

**Comment by nickbabcock** [comment]
> I'm making a mod parser for Stellaris

Small world. Pfim was created for EU3 😄 

#32 solves this. I'll merge it soon and release a patch update soon.

**Comment by draconas1** [comment]
Excellent thanks.  Look forward to the update.

**Comment by nickbabcock** [comment]
Pfim 0.6.0 has been released with this bugfix, thank you for the report.
