### ISSUE TITLE
*.tga loading broken for none square images

### ISSUE THREAD

**Issue by ActuallyaDeviloper** [nickbabcock/Pfim#4]
An uncompressed *.tga file is not loaded completely if it has a different width than height.

I believe [line 15](https://github.com/nickbabcock/Pfim/blob/master/src/Pfim/targa/UncompressedTarga.cs#L15) as well as [line 42](https://github.com/nickbabcock/Pfim/blob/master/src/Pfim/targa/UncompressedTarga.cs#L42) of UncompressedTarga.cs should calculate the image size with `header.Height * stride` instead. There are possibly also other places were this bug is present.

**Comment by nickbabcock** [comment]
If you're up to the task, add a test (eg. add a targa that demonstrates this issue) and update the code. Else I'll take a look maybe tonight.

**Comment by nickbabcock** [comment]
You're right that was an easy fix! I pushed 0.4.1 to nuget and let me know if that works! 🎉

**Comment by ActuallyaDeviloper** [comment]
Thank you for taking care of it so quickly.

Unfortunately we are currently using .Net Framework 4.5 for which reason we were trying to use 0.3.1 of the library.  0.4 of Pfim does not work with .Net Framework 4.5 which is conforming to .Net Standard 1.1 only only instead of 1.3. Can you provide a NuGet distribution where this bug is fixed that will work .Net Framework 4.5?

**Comment by nickbabcock** [comment]
Ah very interesting, I didn't know that .net 4.5 was only compatible with .net standard 1.1.

If you're fine with doing:

```csharp
Stream str = null;
Pfim.Targa.Create(str);
Pfim.Dds.Create(str)
```

Instead of:

```csharp
Pfim.Pfim.FromFile(@"C:\image.dds")
```
I can release this library for .net standard 1.0 and 1.3. How does that sound?

**Comment by ActuallyaDeviloper** [comment]
Sounds good.
We are operating on streams anyway so this is completely fine for us.

**Comment by nickbabcock** [comment]
I have the .net standard 1.0 working locally. I'll push it to nuget tonight.

**Comment by nickbabcock** [comment]
Ok version 0.4.2 is .net standard 1.0 compatible. Let me know how it goes 😄

**Comment by ActuallyaDeviloper** [comment]
I integrated it into an experimental version of our software to replace [the previous library](https://www.codeproject.com/articles/31702/net-targa-image-reader). It seems to work with our test images, let's hope no further issues will arise. 

Thank you very much for dealing with this so quickly!

**Comment by nickbabcock** [comment]
Good to hear. One caveat is that not all targa images are supported (you'll get a `NotImplementedException`). I would add in the code, but I can't find any targa images that are defined in such a way, so if you ever do come across such an image -- let me know! 😄 

And yeah the code project library is slow. In benchmarks I've found Pfim to be 10x-50x faster
