### ISSUE TITLE
Apply colormap by default

### ISSUE THREAD

**Issue by nickbabcock** [nickbabcock/Pfim#42]
Pfim 0.6 introduced `ApplyColorMap` for targa images that contained a colormap. It would make more sense if apply colormap is something that is opt out of (instead of into) like how `decompress` for block compressed dds images. This is something that Pfim 0.7 should do.

**Comment by Krakean** [comment]
@nickbabcock I guess you can do not bother much with colormap support, because tga files that contain color maps these are very rare in practice
