### ISSUE TITLE
FromFile: Extension dependent loading...

### ISSUE THREAD

**Issue by Krakean** [nickbabcock/Pfim#43]
a. Take some DDS image, lets say DXT5.
b. Name it as image.jpg
c. Try Pfim.FromFile("image.jpg")
d. Get the exception.

Curious, is it intentional?
May be it better to make as file header dependent? Lets Pfim quickly analyze header, and by assumption consider it either as DDS or TGA and forward to appropriate function.

**Comment by nickbabcock** [comment]
> Curious, is it intentional?

Yes it's intentional but I know it isn't fool proof. While dds images have a magic number, targa images don't.

I'll mull it over and see if I can come up with something like you suggest.

**Comment by nickbabcock** [comment]
Next version of Pfim will analyze the header of the image before considering the format
