### ISSUE TITLE
Feature request: Pfim.LoadFromStream

### ISSUE THREAD

**Issue by Krakean** [nickbabcock/Pfim#44]
Subj.
Handy, for example, when your game textures are in custom archive/store format and unlikely you will get them from your archive, unpack and place to disk to make then Pfim.FromFile :)

Also something like FromBytes(byte[] data) also could be handy :)

**Comment by nickbabcock** [comment]
Merged PR that adds `Pfim.FromStream`. `FromBytes` can be next 😄
