### ISSUE TITLE
*.tga causes infinite loop in Pfim 0.4.2

### ISSUE THREAD

**Issue by ActuallyaDeviloper** [nickbabcock/Pfim#5]
The attached *.tga file appears to let [TopLeft](https://github.com/nickbabcock/Pfim/blob/595c9cb9ab8b19a5bce238c539a692349d33a6de/src/Pfim/targa/UncompressedTarga.cs#L48) function loop infinitely.
Other imageing software loads the file without problems.

[Problematic File.zip](https://github.com/nickbabcock/Pfim/files/1432185/Problematic.File.zip)

**Comment by nickbabcock** [comment]
Good catch. I have a fix for it. I'll push out Pfim 0.4.3 shortly and comment back when done.

**Comment by nickbabcock** [comment]
Just pushed 0.4.3 to NuGet. I used said image in a test case and it now passes. Thank you for the report! 🎉
