### ISSUE TITLE
Stream is read from offset 0

### ISSUE THREAD

**Issue by LiamKarlMitchell** [nickbabcock/Pfim#67]
Ideally it would start from current location of stream.

**Comment by nickbabcock** [comment]
Let me know if you can elaborate, though it sounds like you already know what you're talking about, so feel free to create a PR with a test case!

**Comment by LiamKarlMitchell** [comment]
For example there is a stream of data, and there is one or more dds files in it with an integer before them saying the length of the dds bytes and perhaps other informations.

```csharp
/// <summary>Create a direct draw image from a stream</summary>
        public static Dds Create(Stream stream, PfimConfig config)
        {
            DdsHeader header = new DdsHeader(stream);
            Dds dds;
```

Well DdsHeader starts from offset 0 not from BaseStream.Position.

```csharp
// <summary>Create header from stream</summary>
        public DdsHeader(Stream stream)
        {
            headerInit(stream);
        }

        private unsafe void headerInit(Stream stream)
        {
            byte[] buffer = new byte[SIZE + 4];
            Reserved1 = new uint[11];
            int bufferSize = stream.Read(buffer, 0, SIZE + 4);
            if (bufferSize != SIZE + 4)
            {
                throw new Exception($"Need at least {SIZE + 4} bytes for a valid DDS header");
            }

```

Wondering what you think.

**Comment by nickbabcock** [comment]
Correct me if I'm wrong, but in `stream.Read(buffer, 0, SIZE + 4);`, the 0 denotes the position to start storing in the buffer, not where to start reading from the stream.

**Comment by LiamKarlMitchell** [comment]
Yeah you are correct maybe I tracked it down wrong.
I'll have to make a test file + script to demonstrate.
