### ISSUE TITLE
DDS - Conversion between formats

### ISSUE THREAD

**Issue by JillCrungus** [nickbabcock/Pfim#68]
Is there any way to use this library to convert DDS image data between formats? Specifically I'm trying to convert a DXT5 image to 8BPP RGBA.

**Comment by nickbabcock** [comment]
Re-encode into a different DDS format? I like that idea, but I don't have plans on adding encoding support at this time.

If you just need to re-encode it (but not into DDS) you can still decode with pfim but use another library to save it (like the ImageSharp sample project)

**Comment by JillCrungus** [comment]
> Re-encode into a different DDS format? I like that idea, but I don't have plans on adding encoding support at this time.
> 
> If you just need to re-encode it (but not into DDS) you can still decode with pfim but use another library to save it (like the ImageSharp sample project)

I just need to be able to encode it into a format that allows me to easily run some processing on every pixel of the image so I can convert the colour space from YCoCg to RGBA

**Comment by nickbabcock** [comment]
Yeah sounds doable. Pfim gives one the pixel data and the format that the data is in, but you'd have to write the conversion layer

**Comment by JillCrungus** [comment]
> Yeah sounds doable. Pfim gives one the pixel data and the format that the data is in, but you'd have to write the conversion layer

I was trying to figure out why the code I wrote wasn't actually working but it turns out that after I create the DDS, the DDS Data array is actually full of nothing but zeroes...

Now stuff is a bit fiddly because the DDS data I'm reading is headerless. So I read the data then construct a header using DirectXTexUtil and stick it at the start of the image data. It's entirely possible something is wrong with the header I'm constructing but Pfim doesn't throw any errors and if I just dump out my full constructed byte array then Microsoft's DirectX Texture Tool seems to open it fine.

The really interesting part is that when I dump out the data to a file and then pass it into Pfim using a FileStream, the Data array actually has data in it as expected.

**Comment by nickbabcock** [comment]
Excellent sounds good!
