### ISSUE TITLE
TGA: unrecognized pixel depth (8/16) exception with some files

### ISSUE THREAD

**Issue by Krakean** [nickbabcock/Pfim#7]
System.Exception: Unrecognized pixel depth: 8 (or 16)
    at Pfim.Targa.get_Format() in d:\_GIT\Csharp-nices\Pfim\src\Pfim\targa\Targa.cs:line 88

Files to test (its 3 of them, all unsupported by Pfim): https://nofile.io/f/u7O05pRD3sK/TGA+File+Examples.rar

**Comment by nickbabcock** [comment]
The color mapped image can be decoded but the color is off in the Pfim.Viewers.Forms as I still need to write the code to interpret the 16bit color map. I created a new issue for this #18
