### ISSUE TITLE
TGA not loaded correctly

### ISSUE THREAD

**Issue by homare** [nickbabcock/Pfim#75]
Hello. I tried to use the pfim in my WPF application.
There were some images that did not load correctly.

https://www.dropbox.com/s/ofy4v09d5uoeikc/tga8.tga?dl=0 Colorless and diagonal
https://www.dropbox.com/s/hzxuwxu38zq7cof/tga24.tga?dl=0 Exception: Value must be non-negative and less than or equal to Int32.MaxValue.(Parameter 'dstOffset') 0x80131502
Those format are TGA 8bpp or 24bpp, 318 x 480 pixel, uncompressed

I think the cause is the stride calculation
TGA does not need 4 pixel padding.

**Comment by nickbabcock** [comment]
Thanks for the report, can these images be committed as test cases or will suitable replacements need to be found?

**Comment by homare** [comment]
Please use it.
