### ISSUE TITLE
How to load TGA Byte Array to Picture Box ?

### ISSUE THREAD

**Issue by Gamer259** [nickbabcock/Pfim#81]
Like I have tga image data loaded in a binary File so I can't use the Pfim.FromFile() method 

Any suggestions ?

**Comment by nickbabcock** [comment]
Yeah see if the following function suit your needs:

```cs
Targa.create(data, new PfimConfig())
```

**Comment by Gamer259** [comment]
How to pass this data then through pfim and then to picture box ??

**Comment by nickbabcock** [comment]
This example should be enough to get you started as it uses a picturebox: https://github.com/nickbabcock/Pfim/blob/35e670b45ef572ab22480a81cf7b435c726f825c/src/Pfim.Viewer.Forms/Form1.cs

**Comment by Gamer259** [comment]
Hi I can't get through 
Manual file loading works but the byte array method not working I think because it is decoding it.

Here see please 
I only have the data of the image without header 

Orange box is the *width* ( 00 01 )
Green box is the *height* ( 00 01 )
Blue box is the *depth* (04 00) 

_*All of these are Int16 value*_

If we convert them we get 

Width = 256
Height = 256 
Depth = 4 

Multiplying these = 262,144 bytes 
This is the image data 

From next yellow offset ( 7b ) till 262,144 bytes 

I want to load this image data in the picture box 

See this image please 
![IMG_20211125_190530](https://user-images.githubusercontent.com/66794499/143451604-1c1df394-3eb6-47f9-bf87-6f3b12d9397f.jpg)

Should I attach the file ?

**Comment by nickbabcock** [comment]
Unfortunately one can't load TGA data without a TGA header. My apologies, I thought the byte array included the TGA header.

**Comment by Gamer259** [comment]
> Unfortunately one can't load TGA data without a TGA header. My apologies, I thought the byte array included the TGA header.

Ok thanks for assistance
