### ISSUE TITLE
TGA: some 32bit cannot be displayed at all

### ISSUE THREAD

**Issue by Krakean** [nickbabcock/Pfim#9]
No exception. Just didn't displayed (at least in default Pfim Viewer):
https://nofile.io/f/0pweeuMvuc5/TGA+File+Examples+3.rar (two files in archive)

**Comment by nickbabcock** [comment]
These files are completely transparent, no? I opened them up in paint.net and both were invisible (ie alpha of 0)

**Comment by Krakean** [comment]
@nickbabcock 
It depends on software I suppose :) 
If you will look at them via Total Commanders "imagine" plugin, you will see something like this:
https://i.imgur.com/U2v9tFc.png

**Comment by nickbabcock** [comment]
Wow yeah you're right -- it does depend.

- Visual studio shows the same as Total Commanders
- GIMP shows the same as Paint.NET (and Pfim).

I'm not sure what to make of this 😕

**Comment by Krakean** [comment]
@nickbabcock 
Well... just for fun, try to import it as DDS texture to some game engine, and lets see what they show :)
For example, try Unity and/or CryEngine..

**Comment by Krakean** [comment]
@nickbabcock 
And just in case, if you interested, this is what Photoshop 2018 shows:
https://i.imgur.com/kabvvsJ.png

**Comment by nickbabcock** [comment]
Haha, this is kinda blowing my mind right now. I'm almost inclined to believe that they are not showing transparency under certain conditions. I created a completely white, but transparent targa image and visual studio is showing just a white square. I save the same image as png and visual studio shows black (transparent). It may be the case that by default photoshop doesn't show [alpha channel for transparent targa images](http://www.alecjacobson.com/weblog/?p=2064)

**Comment by nickbabcock** [comment]
Here's what I've decided. Choosing whether to display the alpha channel is an entirely client side decision. For Windows forms, oftentimes it's as easy as changing:

```c#
case ImageFormat.Rgba32:
    format = PixelFormat.Format32bppArgb;
    break;
```
to
```c#
case ImageFormat.Rgba32:
    format = PixelFormat.Format32bppRgb;
    break;
```

One can make the argument that Pfim should contain a conversion function to drop the alpha channel from the data, but that's currently out of scope of features and may be revisited sometime in the future.
