### ISSUE TITLE
Pfim class has the same name as the Pfim namespace

### ISSUE THREAD

**Issue by ayesc9000** [nickbabcock/Pfim#94]
The Pfim class shares the same name as the Pfim namespace. This is something that should be changed, as this naming causes the namespace and class to collide. While this is legal and will not raise a compile error, it is a dangerous practice that should not be done, especially in a public package.

Here is a four part (!) article on why this practice is bad:
https://docs.microsoft.com/en-us/archive/blogs/ericlippert/do-not-name-a-class-the-same-as-its-namespace-part-one
https://docs.microsoft.com/en-us/archive/blogs/ericlippert/do-not-name-a-class-the-same-as-its-namespace-part-two
https://docs.microsoft.com/en-us/archive/blogs/ericlippert/do-not-name-a-class-the-same-as-its-namespace-part-three
https://docs.microsoft.com/en-us/archive/blogs/ericlippert/do-not-name-a-class-the-same-as-its-namespace-part-four

**Comment by nickbabcock** [comment]
Thanks for pointing it out, I'll mull over a new name to change it to for the next release
